tool(eslint,tsc): Split `lint:workspaces` into `lint:eslint` and `lint:tsc` (internal-pr-421)

diff --git a/.github/workflows/check-codebase.yml b/.github/workflows/check-codebase.yml
--- a/.github/workflows/check-codebase.yml
+++ b/.github/workflows/check-codebase.yml
@@ -10,14 +10,14 @@ jobs:
 
       - uses: ./.github/actions/warm-up-repo
 
-      - name: Run yarn lint:workspaces
+      - name: Run yarn lint:eslint
         if: ${{ success() || failure() }}
         run: |
-          if ! yarn lint:workspaces; then
+          if ! yarn lint:eslint; then
             echo ''
             echo ''
             echo 'ℹ️ ℹ️ ℹ️'
-            echo 'Try running `yarn fix:workspaces` locally to apply autofixes.'
+            echo 'Try running `yarn fix:eslint` locally to apply autofixes.'
             echo 'ℹ️ ℹ️ ℹ️'
             exit 1
           fi
@@ -42,6 +42,19 @@ jobs:
             echo ''
             echo 'ℹ️ ℹ️ ℹ️'
             echo 'Try running `yarn fix:prettier` locally to apply autofixes.'
+            echo 'ℹ️ ℹ️ ℹ️'
+            exit 1
+          fi
+
+      - name: Run yarn lint:tsc
+        if: ${{ success() || failure() }}
+        run: |
+          if ! yarn lint:tsc; then
+            echo ''
+            echo ''
+            echo 'ℹ️ ℹ️ ℹ️'
+            echo 'Please fix the above errors locally for the check to pass.'
+            echo 'If you don’t see them, try merging target branch into yours.'
             echo 'ℹ️ ℹ️ ℹ️'
             exit 1
           fi
