Move validation to the end

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -73,21 +73,6 @@ jobs:
       - name: Setup python
         run: yarn poetry:install
 
-      - name: Validate renovate config
-        if: ${{ success() || failure() }}
-        run: |
-          # Adding renovate in `package.json` causes incompatibility between our dependencies and their dependencies.
-          yarn add -W --dev renovate
-          if ! renovate-config-validator; then
-            echo ''
-            echo ''
-            echo 'ℹ️ ℹ️ ℹ️'
-            echo 'Please fix the above errors locally for the check to pass.'
-            echo 'If you don’t see them, try merging target branch into yours.'
-            echo 'ℹ️ ℹ️ ℹ️'
-            exit 1
-          fi
-
       - name: Run yarn lint:dependency-version-consistency
         if: ${{ success() || failure() }}
         run: |
@@ -376,6 +361,21 @@ jobs:
       - name: Run Playwright tests
         run: |
           yarn test:playwright
+
+      - name: Validate renovate config
+        if: ${{ success() || failure() }}
+        run: |
+          # Adding renovate in `package.json` causes incompatibility between our dependencies and their dependencies.
+          yarn add -W --dev renovate
+          if ! renovate-config-validator; then
+            echo ''
+            echo ''
+            echo 'ℹ️ ℹ️ ℹ️'
+            echo 'Please fix the above errors locally for the check to pass.'
+            echo 'If you don’t see them, try merging target branch into yours.'
+            echo 'ℹ️ ℹ️ ℹ️'
+            exit 1
+          fi
 
       - name: Show external services logs
         if: ${{ success() || failure() }}
